### ISSUE TITLE
spec for MRP object

### ISSUE THREAD

**Issue by mitzimorris** [mitzimorris/mrp-kit#4]

**Comment by jgabry** [comment]
* Takes in two survey objects (sample, population) and a map object
* Fit models using various backends (e.g., `MRP$fit_brms(formula)`)
* Poststratify (e.g., `estimates <- MRP$poststratify(fit)`)
* Plot (e.g., `MRP$plot(estimates)`)

**Comment by jgabry** [comment]
I realized I forgot to post some progress I made on this. I was working locally on my computer but I meant to put it in this issue. This isn't a full spec, but it contains a lot of what we need for the spec (e.g., possible argument names and function signatures), as well as some questions I had when thinking about this. We can go over this when we meet later. 

### To create a new MRP object

```r
# @param sample The SurveyData object (or whatever we call it) containing the sample data and metadata. 
# @param population The SurveyData containing the population data and metadata. 
# @param map The SurveyMap object containing the map between the sample and population.
# @return An R6 object of class "MRP". 

# option 1 (expose the underlying MRP object generator)
x <- MRP$new(sample = SurveyData, population = SurveyData, map = SurveyMap)

# option 2 (function that wraps the internal MRP object generator)
# internally this does MRP$new(sample, population, map)
x <- mrp_setup(sample = SurveyData, population = SurveyData, map = SurveyMap)
```

### Model fitting

```r
# @param ... Arguments other than `data` to pass to the model fitting function.
# @param fun If applicable, a string naming the modeling function to use. For some packages 
#    multiple modeling functions are supported, e.g., stan_glm() and stan_glmer() in rstanarm 
#    and lmer() and glmer() in lme4.
# @return The object returned by the model fitting function. 

fit <- x$fit_brms(...)
fit <- x$fit_rstanarm(fun = "stan_glmer", ...)
fit <- x$fit_lme4(fun = "glmer", ...)


# example usage
fit <- x$fit_rstanarm(
  "stan_glmer", 
  formula = y ~ x + (1|group1) + (1|group2), 
  family = binomial(link = "logit"),
  prior = normal(0,1), 
  prior_covariance = decov(regularization = 2)
)
```

### Poststratification 

If we're only supporting binary outcomes then we just compute the poststratified estimate of Pr(y = 1) for each cell. If we eventually want to include other kinds of models we may want to support predicting into the poststratification matrix. 

Questions: 
* What type of object is returned? Data frame, matrix, etc? 
* How do we handle Bayesian (brms, rstanarm) vs non-Bayesian (lme4) because in the first case there are multiple estimates per cell. 
* Do we also want a method that returns the overall population estimate? 

```r
# @param fit A supported fitted model object. 
# @return Estimates for each poststratification cell. 
estimates <- x$poststratify(fit)
```


### Plotting 

For this I basically just have what we had last time because I realized we need to decide which plots to support before we decide the function signature. Depending on the kinds of plots we support we may need additional arguments. For example, which grouping variable to use. 

```r
# @param estimates The object returned by the poststratify method. 
# @return A ggplot object. 
plot <- x$plot(estimates, ...)
```
