### ISSUE TITLE
rename SurveyQuestion? 

### ISSUE THREAD

**Issue by jgabry** [mitzimorris/mrp-kit#84]
A more appropriate name would be SurveyLink or SurveyContsruct because the object represents the underlying contstruct and links two questions/variables together.

Any other ideas?

**Comment by jgabry** [comment]
After thinking about this a bit more I like `SurveyLink` better than `SurveyConstruct` (I think other people did too if I recall correctly).

**Comment by lauken13** [comment]
What about QuestionLink?

My only worry with SurveyLink is it makes me feel like the whole survey is
being linked! But otherwise I'm fine with it.

**Comment by jgabry** [comment]
> My only worry with SurveyLink is it makes me feel like the whole survey is being linked!

Yeah I know what you mean. Should we ask a few prospective users what they think of a few different options? This is something that we can change easily at any time before the first CRAN release, so there's immediate rush to pick a name I guess.

**Comment by lauken13** [comment]
@Dewi-Amaliah  suggested recode, which could work.

I actually think reflecting on it that it's kinda weird to call it SurveyName (whatever Name turns out to be). I think because this is the only object that is the question and not the survey as a whole, it should probably be QuestionName or ConstructName so our options would be:

QuestionLink
QuestionRecode

ConstructLink
ConstructRecode

(construct defo comes from psych so that might not be intuitve to anyone else).

**Comment by jgabry** [comment]
I was thinking about this some more and it occurred to me that, since a single SurveyMap object consists of many of these maps between pairs of questions, we should just call this object a QuestionMap. 

Regarding the other names, I still think SurveyLink makes sense because it's just referring to one of many links between the surveys, but I agree that it could be misinterpreted. 

I don't think Recode is quite right since the recoding is actually done by the other objects not this one. It's true that this object specifies the connection between questions that will later be used to inform the recoding, but I think it would be misleading to also use Recode in the name for this one.

**Comment by lauken13** [comment]
I like QuestionMap! :)
